- hosts: web
  tasks:
  - name: install httpd service
    package:
     name: "httpd"
     state: present
    when: ansible_distribution == "RedHat"
    register: x
  - name: create document root
    file:
     state: directory
     dest: /var/www/ajay
    register: y
    tags: documentroot
  - name: conf web server
    template: 
     dest: /etc/httpd/conf.d/ajay.conf
     src: template/localconf.j2
    when: x.rc==0
    tags: webconf
    notify: service httpd
  - name: copy web page from url
    get_url:
     dest: "/var/www/ajay"
     url: "https://raw.githubusercontent.com/ajay0988/devops_task3/master/index.html"
    when: y.failed == false
    tags: webgit
  - name: service httpd start 
    service: 
      name: "httpd"
      state: started
  handlers:
  - name: service httpd
    service:
     name: "httpd"
     state: restarted






